server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/.paycoin/h2-db
    username: paycoin
    password: paycoin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /api-docs.html
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    root: info
    org.springframework.web: debug
    org.hibernate.SQL: debug